import { defineConfig } from "drizzle-kit";

// Migrations are generated by drizzle-kit and applied by
// `wrangler d1 migrations apply` (see ADR 0001/README) — no DB credentials
// are needed here.
export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./drizzle",
});
